# .dependabot/config.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    automerge: true
    labels:
      - "npm"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "lodash"
    version: "4.x"
  - package-ecosystem: "rubygems"
    directory: "/"
    schedule:
      interval: "daily"
    automerge: true
    labels:
      - "rubygems"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "rails"
    version: ">= 2"

