name: Lint Test

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint


name: Black Test

on:
  push:
    branches: [main]

jobs:
  black-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Black tests
      run: black --check .


name: Bandit Runner

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run Bandit
      run: |
        source env/bin/activate
        bandit -r .
