name: Security Scan

on:
  push:
    branches: [main]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build image
      run: docker build --tag my-image:latest .
    - name: Scan image for vulnerabilities
      uses: docker/scan-action@v1
      with:
        image-ref: my-image:latest
